// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdowbhmymngydoefwcam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkb3diaG15bW5neWRvZWZ3Y2FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxODU4NjEsImV4cCI6MjA1MTc2MTg2MX0.t1Wmc4aM5oB-8hX-YR6yy7Uy6vW8hz7cHxNuIVmovLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);